version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reversi_backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_USER: ${SMTP_USER}
      SECRET_KEY: ${SECRET_KEY}
    # No exponemos puertos directamente al exterior; Nginx hará de proxy
    ports:
      - "8081:8000"

  frontend:
    build:
      context: ${FRONTEND_CONTEXT:-../reversi_Frontend-Web}
      dockerfile: Dockerfile
    container_name: reversi_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
